- name: delete cygnus-mongo subscriber
  uri:
    url: "http://localhost:8080/orion/v2/subscriptions/{{ subscriber.id }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: "bearer {{ tokens[0] }}"
      Fiware-Service: "{{ fiware.service }}"
      Fiware-ServicePath: "{{ fiware.delivery_robot.service_path }}"
