- name: register device
  uri:
    url: "{{ url.idas.devices }}"
    method: POST
    body_format: json
    status_code: 201
    headers:
      Authorization: "bearer {{ tokens[0] }}"
      Fiware-Service: "{{ fiware.service }}"
      Fiware-ServicePath: "{{ _service_path }}"
    body: "{{ lookup('template', _temp_file) }}"
